---
- name: Install sensu client
  hosts: all
  sudo: True
  gather_facts: True
  tasks:

    - name: Ensure gpg repo key is installed
      apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present

    - name: Ensure needed repositories are present
      apt_repository: repo='deb  http://repos.sensuapp.org/apt sensu main' state=present

    - name: Ensure sensu server is installed
      apt:
        pkg: sensu
        state: latest
        update_cache: yes
        cache_valid_time: 60

    - name: Create sensu ssl directory
      file: path=/etc/sensu/ssl owner=sensu group=sensu mode=0640 state=directory


    - name: Configure sensu client
      template:  
        src: templates/etc/sensu/client/{{ item }}
        dest: /etc/sensu/{{ item }}
        owner: sensu
        group: sensu
        mode: 0644
      with_items:
        - config.json
      when: ansible_hostname != "monitoring"


    - name: Configure sensu client
      template:  
        src: templates/etc/sensu/client/{{ item }}
        dest: /etc/sensu/conf.d/{{ item }}
        owner: sensu
        group: sensu
        mode: 0644
      with_items:
        - client.json


    - name: Latest version of Ruby is installed
      apt: pkg={{ item }} state=latest
      with_items:
        - ruby2.0
        - ruby2.0-dev

    - name: Symlink exists for Ruby 2.0
      file: src=/usr/bin/ruby2.0 dest=/usr/local/bin/ruby state=link

    - name: Symlink exists for Ruby Gems 2.0
      file: src=/usr/bin/gem2.0 dest=/usr/local/bin/gem state=link

    - name: Install sensu plugin
      command: gem install sensu-plugin --no-rdoc --no-ri

    #- name: Create sensu plugin directory for mysql
    #  file: path=/etc/sensu/plugins/mysql state=directory

    # - name: Install mysql sensu checks
    #   get_url: dest=/etc/sensu/plugins/ url=https://raw.github.com/sensu/sensu-community-plugins/master/plugins/{{ item }} mode=0755
    #   with_items:
    #     - mysql/mysql-alive.rb
    #     - mysql/mysql-connections.rb
    #     - mysql/mysql-disk.rb 
    #     - system/check-cpu.rb
    #     - system/check-disk.rb
    #     - system/check-disk.rb
    #     - system/cpu-metrics.rb
    #     - system/memory-metrics.rb
    #     - system/vmstat-metrics.rb 

# Add nagios sonde
    - name: Create nagios directory
      file: path=/etc/sensu/nagios owner=sensu group=sensu mode=0640 state=directory

    - name: Copy nagios sonde
      copy: src=files/etc/sensu/nagios/ dest=/etc/sensu/nagios/ directory_mode=777

    - name: File permissions
      file: path=/etc/sensu/nagios  recurse=yes owner=sensu group=sensu mode=777

# Client configuration


    - name: Ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items: 
        - sensu-client
