---
- name: Configure RabbitMQ server
  connection: local
  hosts: localhost
  sudo: True
  tasks:

    - name: Install EPEL repo.
      yum:
        name: "http://download.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present

    - name: Import EPEL GPG key.
      rpm_key:
        key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
        state: present

   
    - name: ensure rabbitmq server is installed
      yum: 
        pkg: rabbitmq-server 
        state: latest 


    - name: ensure rabbitmq server is stopped
      service: 
        name: rabbitmq-server 
        state: stopped
        enabled: yes

    # - name: install rabbitmq config file that binds to management network interface
    #   template:
    #     src: templates/etc/rabbitmq/rabbitmq-env.conf
    #     dest: /etc/rabbitmq/rabbitmq-env.conf
    #     owner: root
    #     group: root
    #     mode: 0644

    - name: ensure rabbitmq server is started and enabled
      service: 
        name: rabbitmq-server 
        state: restarted 
        enabled: yes

    - name: ensure anonymous guest user is absent
      rabbitmq_user: 
        user: guest 
        state: absent

    - name: Ensure sensu vhost is present
      rabbitmq_vhost:
        name: /sensu
        state: present

    - name: Ensure sensu user is present
      rabbitmq_user:
        user: sensu
        password: "vjM,HAf,Gp_9QlLxOjaA" 
        vhost: /sensu
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
        force: yes

    - name: Ensure admin user is present
      rabbitmq_user:
        user: admin
        password: admin
        vhost: /sensu
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
        force: yes

    - name: Set tag for admin user
      command: rabbitmqctl set_user_tags admin administrator

    - name: ensure rabbitmq server is started and enabled
      service: 
        name: rabbitmq-server 
        state: restarted 
        enabled: yes